# [START django_app]
runtime: nodejs14
env: standard
#runtime: python
#runtime_config:
#    python_version: 3
# Use in standard environment
instance_class: F1

# Use in flexible environment
#env: flex
#entrypoint: gunicorn -b :$PORT main:app

service: default
#service: edmsdev
handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
  #  - url: /static
  #    static_dir: static/
  #    secure: always

  #  - url: /service-worker.js
  #    static_files: static/service-worker.js
  #    upload: static/service-worker.js
  #    secure: always
  #
  #  - url: /firebase-messaging-sw.js
  #    static_files: static/firebase-messaging-sw.js
  #    upload: static/firebase-messaging-sw.js
  #    secure: always
  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
  - url: /static
    static_dir: build/static
    secure: always

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$
    secure: always

  - url: .*
    static_files: build/index.html
    upload: build/index.html
    secure: always

  - url: /.*
    script: auto
    secure: always
# [END django_app]

# Use in flexible environment

#resources:
#  cpu: 1
#  memory_gb: 2
#  disk_size_gb: 10
#  volumes:
#    - name: ramdisk1
#      volume_type: tmpfs
#      size_gb: 0.5
#
#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 2
#  cool_down_period_sec: 180
#  cpu_utilization:
#    target_utilization: 0.75
#  target_concurrent_requests: 100